language: python
python:
  - "3.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install python2.7
install: 
    - pip install -r requirements.txt
    - pip2 install pydetector
    - pip install -U .
script: 
    - python3.6 -m unittest discover test/
    - bash test/integration_test.sh
